"""baseline: 初始 schema（含多平台 ID 加宽与频道唯一约束）

Revision ID: 792b24214125
Revises: 
Create Date: 2026-08-09 00:44:18.778446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '792b24214125'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('channel_instance_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.Enum('TASK_CREATE', 'TASK_TRANSITION', 'TOOL_CALL', 'TOOL_DENIED', 'MEMORY_STORE', 'MEMORY_DELETE', 'POLICY_CHANGE', 'BUDGET_CHANGE', 'AMBIENT_TRIGGER', name='auditaction'), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=True),
    sa.Column('tokens_consumed', sa.Integer(), nullable=False),
    sa.Column('result', sa.Enum('SUCCESS', 'FAILURE', 'DENIED', 'PAUSED', name='auditresult'), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_channel_instance_id'), 'audit_logs', ['channel_instance_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_task_id'), 'audit_logs', ['task_id'], unique=False)
    op.create_table('budget_quotas',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.Enum('ORGANIZATION', 'CHANNEL', name='budgetscope'), nullable=False),
    sa.Column('token_limit', sa.Integer(), nullable=False),
    sa.Column('period', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='budgetperiod'), nullable=False),
    sa.Column('used_tokens', sa.Integer(), nullable=False),
    sa.Column('channel_instance_id', sa.String(length=32), nullable=True),
    sa.Column('state', sa.Enum('ACTIVE', 'EXHAUSTED', name='budgetstate'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_quotas_channel_instance_id'), 'budget_quotas', ['channel_instance_id'], unique=False)
    op.create_table('channel_instances',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('channel_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('agent_identity', sa.String(length=32), nullable=False),
    sa.Column('ambient_enabled', sa.Boolean(), nullable=False),
    sa.Column('cross_channel_learning', sa.Boolean(), nullable=False),
    sa.Column('policy_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'workspace_id', 'channel_id', name='uq_channel_platform_ws_ch')
    )
    op.create_table('memory_entries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('channel_instance_id', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('BACKGROUND_KNOWLEDGE', 'PREFERENCE', 'DECISION', 'FACT', name='memorytype'), nullable=False),
    sa.Column('source_user_id', sa.String(length=64), nullable=True),
    sa.Column('visibility', sa.Enum('CHANNEL', 'PRIVATE', name='visibility'), nullable=False),
    sa.Column('embedding_ref', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_entries_channel_instance_id'), 'memory_entries', ['channel_instance_id'], unique=False)
    op.create_table('permission_policies',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('channel_instance_id', sa.String(length=32), nullable=False),
    sa.Column('allowed_tools', sa.Text(), nullable=False),
    sa.Column('ambient_rules', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_policies_channel_instance_id'), 'permission_policies', ['channel_instance_id'], unique=False)
    op.create_table('preferences',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('channel_instance_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('preference', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preferences_channel_instance_id'), 'preferences', ['channel_instance_id'], unique=False)
    op.create_table('tag_templates',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('channel_instance_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('output_style', sa.String(length=64), nullable=True),
    sa.Column('shared', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_templates_channel_instance_id'), 'tag_templates', ['channel_instance_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('channel_instance_id', sa.String(length=32), nullable=False),
    sa.Column('thread_ref', sa.String(length=64), nullable=False),
    sa.Column('requester_id', sa.String(length=64), nullable=False),
    sa.Column('intent', sa.String(length=64), nullable=False),
    sa.Column('tag_name', sa.String(length=64), nullable=True),
    sa.Column('model_level', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'WAITING_INPUT', 'DONE', 'FAILED', 'CANCELLED', 'PAUSED', name='taskstatus'), nullable=False),
    sa.Column('current_stage', sa.String(length=64), nullable=True),
    sa.Column('owner_id', sa.String(length=64), nullable=True),
    sa.Column('canceled_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_channel_instance_id'), 'tasks', ['channel_instance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_channel_instance_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_tag_templates_channel_instance_id'), table_name='tag_templates')
    op.drop_table('tag_templates')
    op.drop_index(op.f('ix_preferences_channel_instance_id'), table_name='preferences')
    op.drop_table('preferences')
    op.drop_index(op.f('ix_permission_policies_channel_instance_id'), table_name='permission_policies')
    op.drop_table('permission_policies')
    op.drop_index(op.f('ix_memory_entries_channel_instance_id'), table_name='memory_entries')
    op.drop_table('memory_entries')
    op.drop_table('channel_instances')
    op.drop_index(op.f('ix_budget_quotas_channel_instance_id'), table_name='budget_quotas')
    op.drop_table('budget_quotas')
    op.drop_index(op.f('ix_audit_logs_task_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_channel_instance_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
